library(dplyr)
library(tidyr)
library(ggplot2)
data=read.csv("C:/Users/shree/Documents/R final programming/train.csv")
#print(summary(data))
print(ggplot(data,aes(x=Age))+geom_histogram(fill="blue",color="black",binwidth = 5)+labs(title="Histogram",x="Age",y="frequency"))
print(ggplot(data,aes(x=factor(Survived),fill=factor(Survived)))+geom_bar()+labs(titile="Bar graph",x="Survived",y="frequency")+scale_fill_manual(values = c("red","green")))
missingvalues=colSums(is.na(data))      
print(missingvalues)
data$Age[is.na(data$Age)]=mean(data$Age,na.rm=TRUE)
missingvalues2=colSums(is.na(data))
print(missingvalues2)
#fileter data
filterdata=filter(data,Age>18)
#print(filterdata)
sorted=arrange(data,desc(Fare))
print(sorted)
A=read.csv("C:/Users/shree/Documents/R final programming/A.csv")
B=read.csv("C:/Users/shree/Documents/R final programming/B.csv")
mergeddata=merge(A,B,by.x="PassengerId",by.y="PassengerId")
print(colnames(mergeddata))
print(head(data))
test=t.test(Age~Survived,data=data)
print(test)
correlation=cor(data$Age,data$Fare)
print(correlation)
boxplot(Age ~ Survived, data = data, col = c("red", "blue"), main = "Boxplot of Age by Survived")
