library(ggplot2)
library(dplyr)
library(tidyr)
library(plotly)
data=read.csv("C:/Users/shree/Documents/R final programming/train.csv")
print(head(data))
data$Survived=factor(data$Survived,levels = c("0","1"))
barchart=ggplot(data,aes(x=factor(Pclass),fill=factor(Survived)))+geom_bar(position = "dodge")+labs(x="Pclass",y="survived",title="Bar chart",fill="Survived")+scale_fill_manual(values = c("0"="red","1"="blue"))
#print(barchart)
lineplot=ggplot(data,aes(x=Age,y=after_stat(density)))+geom_density(fill="blue",alpha=0.5)+labs(title = "lineplot",x="Age",y="density")
#print(lineplot)
scatterplot <- ggplot(data, aes(x = Age, y = Fare, color = factor(Survived))) +geom_point() +scale_color_manual(values = c("0" = "red", "1" = "blue"))+labs(color = "Survived")
#print(scatterplot)
heatmap=ggplot(data,aes(x=Pclass,y=Survived))+stat_bin2d(bins = 10,aes(fill=after_stat(count)))+labs(fill="frequency")+scale_fill_continuous(name="frequency",low="white",high="blue")+theme_minimal()
#print(heatmap)
interbar=ggplotly(barchart)
interline=ggplotly(lineplot)
interscatter=ggplotly(scatterplot)
interheatmap=ggplotly(heatmap)

ggsave("barplot.png",plot=barchart,width = 8,height = 6)
ggsave("lineplot.png",plot=lineplot,width = 8,height = 6)
ggsave("scatterplot.png",plot=scatterplot,width = 8,height = 6)
ggsave("heatmap.png",plot=heatmap,width = 8,height = 6)
htmlwidgets::saveWidget(interbar,"interactive_barchart.html",selfcontained = TRUE)
htmlwidgets::saveWidget(interline,"interactive_lineplot.html",selfcontained = TRUE)
htmlwidgets::saveWidget(interscatter,"interactive_scatterplot.html",selfcontained = TRUE)
htmlwidgets::saveWidget(interheatmap,"interactive_heatmap.html",selfcontained = TRUE)